export * from './work.service';
export * from './education.service';
export * from './skill.service';
export * from './organization.service';
export * from './family.service';
export * from './reference.service';
export * from './language.service';
export * from './doctype.service';
export * from './medical.service';