export * from './work.controller';
export * from './education.controller';
export * from './skill.controller';
export * from './organization.controller';
export * from './family.controller';
export * from './reference.controller';
export * from './language.controller';
export * from './doctype.controller';
export * from './medical.controller';